### ISSUE TITLE
Sort out CSS Styling on post

### ISSUE THREAD

**Issue by mikechristopher** [mikechristopher/100daysofcode#3]
https://github.com/mikechristopher/100daysofcode/blob/54f5aebf3f00a6376a43ded180db4085e4332c52/_layouts/post.html#L11-L11

Sort out the styling on the post page - scope out design layout and test

**Comment by Shubham-kumar799** [comment]
Hi @mikechristopher , 
I am new to open source and would like to work on the issue if its ok with you.
i would be great if you could elaborate what sort of styling would you like by sharing any  links or pictures

**Comment by mikechristopher** [comment]
> Hi @mikechristopher ,
> I am new to open source and would like to work on the issue if its ok with you.
> i would be great if you could elaborate what sort of styling would you like by sharing any links or pictures

Hi @Shubham-kumar799 
Thank you for the offer but this is more of a personal project as relatively new to it all myself so learning as I go and the issues were more to test the workflow whilst making reminders for myself.
:)
